### ISSUE TITLE
Compatibily of full() empty() VivadoHLS methods for Stream class

### ISSUE THREAD

**Issue by diamantopoulos** [definelicht/hlslib#11]
It would be nice to add the full() and empty()methods, so that we have less changes in the code when we use hlslib to wrap hls streams (i.e. instead of having to change to Isfull() and isEmpty()). This addition to Stream.h is working for me:

```
  // Compatibility with Vivado HLS interface
  bool empty() {
    #pragma HLS INLINE
    return IsEmpty();
  }

  bool full() {
    #pragma HLS INLINE
    return IsFull();
  }
```
thanks
--d

**Comment by definelicht** [comment]
@diamantopoulos Thanks for the suggestion, I added this with 8284bf2.

**Comment by diamantopoulos** [comment]
@definelicht thx, can we also add the `read(var)` method. i.e. read with argument, in addition to `read()` already provided. This works for me:

```
  void read(T &output) {
    #pragma HLS INLINE
    output = read();
  }
```

**Comment by definelicht** [comment]
@diamantopoulos Added this also

**Comment by diamantopoulos** [comment]
@definelicht cool, thanks!
