### ISSUE TITLE
Warnings when building with 2020.2

### ISSUE THREAD

**Issue by derpda** [definelicht/hlslib#36]
Hey ‪Johannes!

I'm still using your hlslib with great success for my work, so once again thank you!

I am currently trying to reduce the amount of warnings I get from my build.
Some of the remaining warnings are stemming from hlslib, in particular from the following two places:

### Resource pragma
`#pragma HLS Resource` seems to have been deprecated in 2020.2, so the following code produces warnings like
```
WARNING: [HLS 207-5510] 'Resource pragma' is deprecated, and it will be removed in future release. 
It is suggested to replace it with 'bind_op/bind_storage pragma'.: 
/home/dev/hlslib/include/hlslib/xilinx/Stream.h:500:9
```
https://github.com/definelicht/hlslib/blob/38c612d88605c7e88a42771889dc7b041d9ca747/include/hlslib/xilinx/Stream.h#L495-L507
#### Possible solution 
```c++
  Stream(char const *const name) : Stream<T, 0, storage>(name, depth, storage) {
    #pragma HLS INLINE
#if !defined(__VIVADO_HLS__) || defined(__VITIS_HLS__)
    #pragma HLS STREAM variable=this->stream_ depth=depth
    if (storage == Storage::BRAM) {
      #pragma HLS bind_storage variable=this->stream_ type=FIFO impl=BRAM
    } else if (storage == Storage::LUTRAM) {
      #pragma HLS bind_storage variable=this->stream_ type=FIFO impl=LUTRAM
    } else if (storage == Storage::SRL) {
      #pragma HLS bind_storage variable=this->stream_ type=FIFO impl=SRL
    }
#endif
  }
```
However, this might have to be wrapped in conditions checking the Vitis HLS version...

### Unused parameter
During synthesis, the following code produces "unused parameter" warnings:
```
WARNING: [HLS 207-5301] unused parameter 'name': /home/dev/hlslib/include/hlslib/xilinx/Stream.h:354:35
```
https://github.com/definelicht/hlslib/blob/38c612d88605c7e88a42771889dc7b041d9ca747/include/hlslib/xilinx/Stream.h#L354-L358
#### Possible solution
```c++
#ifndef HLSLIB_SYNTHESIS
  void set_name(char const *const name) {
    name_ = name;
#else
  void set_name(char const *const) {
#endif
  }
```

**Comment by definelicht** [comment]
Thanks! I merged the PR as is: I'm anyway reducing the support for older versions, since it's a lot of effort to maintain mostly unused versions. It's still possible to use an old tag if using SDAccel or SDx rather than Vitis.
