### ISSUE TITLE
function WriteOptimistic in Stream.h has a void return type

### ISSUE THREAD

**Issue by sarahelghandour** [definelicht/hlslib#52]
Hi, 

I think the below function in Stream.h should have the type bool not void.

Regards,
Sarah

  void WriteOptimistic(T const &val) {
    #pragma HLS INLINE
#ifndef HLSLIB_SYNTHESIS
    #pragma HLS INLINE
    return WriteOptimistic(val, depth_);
#else
    return WriteOptimistic(val, std::numeric_limits<int>::max());
#endif
  }

**Comment by definelicht** [comment]
Hi, maybe you're thinking of the non-blocking version of write, which is called `WriteNonBlocking`? Or why would you expect a boolean return type?

**Comment by sarahelghandour** [comment]
Oh sorry, I think I didn't grasp the code properly yet. Sorry for the confusion.

**Comment by definelicht** [comment]
No worries
