### ISSUE TITLE
Any plans to support Vitis 2022.1 and 2022.2?

### ISSUE THREAD

**Issue by remifan** [definelicht/hlslib#65]
Hi, hlslib is an interesting project, thanks for the great work!

Would you have plans to support Vitis 2022.1 and 2022.2?

**Comment by definelicht** [comment]
Hey @remifan! Since I'm no longer working with FPGAs I can invest only limited time, but you can help me if you let me know what problems exist that need to be fixed :-)

**Comment by remifan** [comment]
Thanks for the great effort! I just realized your master branch now support 2022.2 (using fpo_v7_1). Will you consider publishing a new release? so that other project may upgrade to stay compatible. Thanks!
